version: '3.8'

services:
  backend:
    image: node:14.10.1-alpine
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment: 
      - CHOKIDAR_USEPOLLING=true
      
  # nginx:
  #   depends_on:
  #     - backend
  #     - frontend
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "3050:80"
  #   expose:
  #     - "3050"